### PR TITLE
Release 1.0.2

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Release 1.0.2
| Type?         | 
| BC breaks?    | 
| Deprecations? | 
| Fixed ticket? | 
| How to test?  |

### CODE REVIEW

**Review by zuk3975 — APPROVED** [review]

**Comment by sallemiines** [comment]
Hello @Hlavtox 

Thanx for the PR ! 

I noticed that the version of the new release should be `1.0.2 `but after installing the PR I see that the version is still `1.0.1`!

Release-1-0-2-by-Hlavtox-·-Pull-Request-11-·-PrestaShop-ps_specials


Module-manager-•-1787 (6)

Release-1-0-2-by-Hlavtox-·-Pull-Request-11-·-PrestaShop-ps_specials (1)

Could you please check and feedback ? ! 

Thank you .

**Comment by Hlavtox** [comment]
Fixed @sallemiines, you can recheck

**Comment by sallemiines** [comment]
> Fixed @sallemiines, you can recheck

@Hlavtox thanx for the quick fix ! 

PR LGTM QA :heavy_check_mark: 

Module-manager-•-1787 (7)


https://user-images.githubusercontent.com/31663369/213187672-7d900c7e-d089-47b0-8366-cda2cc848679.mp4

Thank you ! :rocket:

**Comment by Hlavtox** [comment]
Aaay 🚀 Thank yoooou

**Pull request merged**
